In [1]:
2*2

4

In [5]:
In[1]

'In[1]'

In [6]:
Out[1]

'In[1]'

In [7]:
In

['', 'In[1]', 'Out[1]', 'In', 'Out', 'In[1]', 'Out[1]', 'In']

In [8]:
Out

{1: 'In[1]',
 2: 'In[1]',
 3: ['', 'In[1]', 'Out[1]', 'In', 'Out', 'In[1]', 'Out[1]', 'In', 'Out'],
 5: 'In[1]',
 6: 'In[1]',
 7: ['', 'In[1]', 'Out[1]', 'In', 'Out', 'In[1]', 'Out[1]', 'In', 'Out']}

In [7]:
1 + 2

3

In [8]:
x = 1 ; # Output blocked by ;

In [9]:
2

2

In [10]:
# import os : Autocompletion and Object Introspection

In [9]:
import math 
math.cos?

Signature: math.cos(x, /)
Docstring: Return the cosine of x (measured in radians).
Type:      builtin_function_or_method


In [16]:
# File navigation 
# !dir (Windows)
# !ls (Unix)

In [24]:
def fib(n):
    
     """
     Return a list of the first n Fibonacci numbers.
     """
        
     f0, f1 = 0, 1
     f = [1] * n
        
     for i in range(1, n):
         f[i] = f0 + f1
         f0, f1 = f1, f[i]
        
     return f

print(fib(10))

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


In [8]:
# Debugger

# fib(1.0)

In [ ]:
%debug

> <magic-timeit>(1)inner()



In [ ]:
# %reset

"""
The %reset command provides this 
functionality (use the flag –f to force the reset). Using this command can often eliminate the need for 
otherwise common exit–restart cycles of the console. Although it is necessary to reimport modules after 
the %reset command has been used, it is important to known that even if the modules have changed since 
the last import, a new import after a %reset will not import the new module but rather reenable a cached 
version of the module from the previous import. When developing Python modules, this is usually not the 
desired behavior. In that case, a reimport of a previously imported (and since updated) module, can often be 
achieved by using the dreload function.

"""

In [3]:
# %timeit fib(100)

In [4]:
#  %time result = fib(100)

In [6]:
import numpy as np
def random_walker_max_distance(M, N):
    """
     Simulate N random walkers taking M steps, and return the largest distance
     from the starting point achieved by any of the random walkers.
     """
    trajectories = [np.random.randn(M).cumsum() for _ in range(N)]
    return np.max(np.abs(trajectories))

In [7]:
 %prun random_walker_max_distance(400, 10000)

# 1. The Numpy Array Object

In [13]:
# The numpy array object

import numpy as np
data = np.array([[1, 2], [3, 4], [5, 6]])
type(data)

numpy.ndarray

In [3]:
"""
shape A tuple that contains the number of elements (i.e., the length) for each dimension (axis) 
of the array.
size The total number of elements in the array.
ndim Number of dimensions (axes).
nbytes Number of bytes used to store the data.
dtype The data type of the elements in the array
"""

'\nshape A tuple that contains the number of elements (i.e., the length) for each dimension (axis) \nof the array.\nsize The total number of elements in the array.\nndim Number of dimensions (axes).\nnbytes Number of bytes used to store the data.\ndtype The data type of the elements in the array\n'

In [4]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
data.ndim

2

In [7]:
data.shape

(3, 2)

In [9]:
data.size

6

In [10]:
data.size

6

In [11]:
data.nbytes

24

In [12]:
"""
int int8, int16, int32, int64 Integers.
uint uint8, uint16, uint32, uint64 Unsigned (non-negative) integers.
bool bool Boolean (True or False).
float float16, float32, float64, float128 Floating-point numbers.
complex complex64, complex128, complex256 Complex-valued floating-point numbers.
"""

'\nint int8, int16, int32, int64 Integers.\nuint uint8, uint16, uint32, uint64 Unsigned (non-negative) integers.\nbool bool Boolean (True or False).\nfloat float16, float32, float64, float128 Floating-point numbers.\ncomplex complex64, complex128, complex256 Complex-valued floating-point numbers.\n'

In [14]:
# Data Types

In [18]:
data = np.array([1, 2, 3], dtype=float)
data

array([1., 2., 3.])

In [19]:
data.dtype

dtype('float64')

In [20]:
# Complex Numbers

In [26]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [27]:
(d1 + d2).dtype

dtype('complex128')

In [32]:
data = np.array([1, 2, 3], dtype=complex)
print("Data : ",data)
print("Real Part : ",data.real)
print("Imaginary Part : ",data.imag)

Data :  [1.+0.j 2.+0.j 3.+0.j]
Real Part :  [1. 2. 3.]
Imaginary Part :  [0. 0. 0.]


# Creating Arrays

In [34]:
np.array([1, 2, 3, 4])
data.ndim

1

In [39]:
new_array = np.array([[1, 2], [3, 4]])

In [40]:
new_array.ndim

2

In [41]:
new_array.shape

(2, 2)

In [42]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [44]:
np.logspace(0, 2, 5) 

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [47]:
# Meshgrid Arrays
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X,Y = np.meshgrid(x, y)

In [48]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [49]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [50]:
Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]], dtype=int32)

In [51]:
# Creating Uninitialized Arrays
np.empty(3, dtype=np.float)

C:\Users\golam\AppData\Local\Temp\ipykernel_55996\3813404062.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.empty(3, dtype=np.float)


array([0., 0., 0.])

In [53]:
# Creating Arrays with Properties of Other Arrays

def f(x):
    
     y = np.ones_like(x)
     # compute with x and y
    
     return y
    
"""
At the first line of the body of this function, a new array y is created using np.ones_like, which results 
in an array of the same size and data type as x, and filled with ones.

"""


'\nAt the first line of the body of this function, a new array y is created using np.ones_like, which results \nin an array of the same size and data type as x, and filled with ones.\n\n'

In [54]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
 np.eye(3, k=1)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [56]:
 np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [145]:
 np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

# 3. Indexing and Slicing

In [58]:
"""
a[m] Select element at index m, where m is an integer (start counting form 0).
a[-m] Select the mth element from the end of the list, where m is an integer. The last 
element in the list is addressed as -1, the second-to-last element as -2, and so on.
a[m:n] Select elements with index starting at m and ending at n −1 (m and n are integers).
a[:] or a[0:-1] Select all elements in the given axis.
a[:n] Select elements starting with index 0 and going up to index n −1 (integer).
a[m:] or a[m:-1] Select elements starting with index m (integer) and going up to the last element in 
the array.
a[m:n:p] Select elements with index m through n (exclusive), with increment p.
a[::-1] Select all the elements, in reverse order

"""

'\na[m] Select element at index m, where m is an integer (start counting form 0).\na[-m] Select the mth element from the end of the list, where m is an integer. The last \nelement in the list is addressed as -1, the second-to-last element as -2, and so on.\na[m:n] Select elements with index starting at m and ending at n −1 (m and n are integers).\na[:] or a[0:-1] Select all elements in the given axis.\na[:n] Select elements starting with index 0 and going up to index n −1 (integer).\na[m:] or a[m:-1] Select elements starting with index m (integer) and going up to the last element in \nthe array.\na[m:n:p] Select elements with index m through n (exclusive), with increment p.\na[::-1] Select all the elements, in reverse order\n\n'

In [60]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
B = A[A > 5]
B

array([6, 7, 8, 9])

In [63]:
B[0] = -1 # this does not affect A
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
B

array([-1,  7,  8,  9])

In [66]:
A[A > 5] = -1
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

In [67]:
# Reshaping and Resizing

In [68]:
data = np.array([[1, 2], [3, 4]])

In [69]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [71]:
data.reshape(4)

array([1, 2, 3, 4])

In [72]:
# Multidimensional Arrays

In [74]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [75]:
A.shape

(6, 6)

In [76]:
A.ndim

2

In [77]:
A.size

36

In [78]:
 A[:, 1] # the second column

array([ 1, 11, 21, 31, 41, 51])

In [79]:
 A[1, :] # the second row

array([10, 11, 12, 13, 14, 15])

In [80]:
A[:3, :3] # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [81]:
A[3:, :3] # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [82]:
 A[::2, ::2] # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [83]:
A[1::2, 1::3] # every second and third element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

In [109]:
# View and Copy while slicing

In [110]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [113]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [112]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [14]:
import numpy as np
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
B = A[1:5, 1:5]
B[:, :] = 0 # Changing B changes A
B   

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [15]:

"""
Here, assigning new values to the elements in an array B, which is created from the array A, also 
modifies the values in A (since both arrays refer to the same data in the memory). The fact that extracting 
subarrays results in views rather than new independent arrays eliminates the need for copying data and 
improves performance. When a copy rather than a view is needed, the view can be copied explicitly by using 
the copy method of the ndarray instance
"""
A # A is changed as B has been changed

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [117]:
# copy

In [118]:
C = B[1:3, 1:3].copy()

In [119]:
C

array([[0, 0],
       [0, 0]])

In [120]:
C[:, :] = 1 # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [121]:
C

array([[1, 1],
       [1, 1]])

In [122]:
"""
In addition to the copy attribute of the ndarray class, an array can also be copied using the function 
np.copy, or, equivalently, using the np.array function with the keyword argument copy=True
"""

B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
A = np.linspace(0, 1, 11) 
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [17]:
A[[0, 2, 4]] # The same thing can be accomplished by indexing with a Python list

array([0. , 0.2, 0.4])

In [18]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [19]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [20]:
# Fancy Indexing and Boolean-valued Indexin

In [21]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [131]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [132]:
A[[0, 2, 4]] # The same thing can be accomplished by indexing with a Python list

array([0. , 0.2, 0.4])

In [22]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [23]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [136]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
indices = [2, 4, 6]
B = A[indices]
print("Inital value of B", B)
B[0] = -1 # this does not affect A
print("Final value of B : ", B)
A

Inital value of B [0.2 0.4 0.6]
Final value of B :  [-1.   0.4  0.6]


array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [25]:
A[indices] = -1
A # now A is changed

array([ 0. ,  0.1, -1. ,  0.3, -1. ,  0.5, -1. ,  0.7,  0.8,  0.9,  1. ])

In [143]:
A = np.arange(10)
print("A:", A)
B = A[A > 5]
B[0] = -1 # this does not affect A
A

A: [0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshaping and Resizing

In [3]:
import numpy as np

data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [4]:
data.ndim

2

In [5]:
data.shape

(2, 2)

In [15]:
a = np.reshape(data, (1, 4)) # reshaping . note that it's view, not copy. changing a will change data
a

array([[1, 2, 3, 4]])

In [16]:
data.reshape(4) # second reshaping

array([1, 2, 3, 4])

In [17]:
data # original data is same even after reshaping and saving the value inside a

array([[1, 2],
       [3, 4]])

Broadcasting

In [147]:
import numpy as np
# Let's create an array using arange()
array_1d = np.arange(0, 10)
print("Original Array : ", array_1d)
array_1d[0:5] = 500
print("After Broadcasting : ", array_1d)

Original Array :  [0 1 2 3 4 5 6 7 8 9]
After Broadcasting :  [500 500 500 500 500   5   6   7   8   9]


In [148]:
import numpy as np
# Lets create a 2D martix with ones
array_2d = np.ones((4, 4))

print("2D Array")
print(array_2d)

# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
print("\n After Broadcasting")
print(array_2d)


2D Array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 After Broadcasting
[[300. 300. 300. 300.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]


Ravel and Flatten

In [19]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [22]:
data.shape

(2, 2)

In [20]:
data.flatten()

array([1, 2, 3, 4])

In [21]:
data.flatten().shape

(4,)

In [3]:
# new axis
import numpy as np
data = np.arange(0, 5)
data

array([0, 1, 2, 3, 4])

In [6]:
data.shape

(5,)

In [4]:
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [5]:
column.shape

(5, 1)

In [8]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

In [9]:
row.shape

(1, 5)

In [11]:
# Stack
data = np.arange(5)
data
np.array([0, 1, 2, 3, 4])
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [13]:
data = np.arange(5)
data
np.array([0, 1, 2, 3, 4])
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [15]:
"""
This indeed stacks the arrays horizontally, but not in the way intended here. To make np.hstack treat 
the input arrays as columns and stack them accordingly, we need to make the input arrays two-dimensional 
arrays of shape (1, 5) rather than one-dimensional arrays of shape (5,). As discussed earlier, we can insert 
a new axis by indexing with np.newaxis:
"""

'\nThis indeed stacks the arrays horizontally, but not in the way intended here. To make np.hstack treat \nthe input arrays as columns and stack them accordingly, we need to make the input arrays two-dimensional \narrays of shape (1, 5) rather than one-dimensional arrays of shape (5,). As discussed earlier, we can insert \na new axis by indexing with np.newaxis:\n'

In [16]:
data = data[:, np.newaxis]
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [14]:
"""
The number of elements in a NumPy array cannot be changed once the array has been created. To 
insert, append, and remove elements from a NumPy array, for example, using the function np.append, 
np.insert, and np.delete, a new array must be created and the data copied to it. It may sometimes be 
tempting to use these functions to grow or shrink the size of a NumPy array, but due to the overhead of 
creating new arrays and copying the data, it is usually a good idea to preallocate arrays with size such that 
they do not later need to be resized.
"""

'\nThe number of elements in a NumPy array cannot be changed once the array has been created. To \ninsert, append, and remove elements from a NumPy array, for example, using the function np.append, \nnp.insert, and np.delete, a new array must be created and the data copied to it. It may sometimes be \ntempting to use these functions to grow or shrink the size of a NumPy array, but due to the overhead of \ncreating new arrays and copying the data, it is usually a good idea to preallocate arrays with size such that \nthey do not later need to be resized.\n'

# 5. Vectorized Expressions

In [17]:
"""
NumPy implements functions and vectorized 
operations corresponding to most fundamental mathematical functions and operators. 
"""

'\nNumPy implements functions and vectorized \noperations corresponding to most fundamental mathematical functions and operators. \n'

In [24]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [26]:
y = np.array([[5, 6], [7, 8]])
y

array([[5, 6],
       [7, 8]])

Arithmetic Operations

In [19]:
x + y

array([[ 6,  8],
       [10, 12]])

In [21]:
y - x

array([[4, 4],
       [4, 4]])

In [22]:
x*y

array([[ 5, 12],
       [21, 32]])

In [27]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [28]:
2*x

array([[2, 4],
       [6, 8]])

In [29]:
2**x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [37]:
import numpy as np
x = np.array([1, 2, 3, 4]).reshape(2, 2)
z = np.array([1, 2, 3, 4])
# error : problem with shape
x / z

ValueError: operands could not be broadcast together with shapes (2,2) (4,) 

In [42]:
"""
The two expressions have the same effect, but in the first case x is reassigned to a new array, while in the 
second case the values of array x are updated in place. Extensive use of in-place operators tends to impair 
code readability, and in-place operators should therefore be used only when necessary.
"""


'\nThe two expressions have the same effect, but in the first case x is reassigned to a new array, while in the \nsecond case the values of array x are updated in place. Extensive use of in-place operators tends to impair \ncode readability, and in-place operators should therefore be used only when necessary.\n'

In [43]:
x = np.arange(5)
y = np.arange(5)

x += y
x

array([0, 2, 4, 6, 8])

In [44]:
x = np.arange(5)
y = np.arange(5)

z = x + y
z

array([0, 2, 4, 6, 8])

Elementwise Functions

In [45]:
"""
np.cos, np.sin, np.tan Trigonometric functions.
np.arccos, np.arcsin. np.arctan Inverse trigonometric functions.
np.cosh, np.sinh, np.tanh Hyperbolic trigonometric functions.
np.arccosh, np.arcsinh, np.arctanh Inverse hyperbolic trigonometric functions.
np.sqrt Square root.
np.exp Exponential.
np.log, np.log2, np.log10 Logarithms of base e, 2, and 10, respectively.
"""


'\nnp.cos, np.sin, np.tan Trigonometric functions.\nnp.arccos, np.arcsin. np.arctan Inverse trigonometric functions.\nnp.cosh, np.sinh, np.tanh Hyperbolic trigonometric functions.\nnp.arccosh, np.arcsinh, np.arctanh Inverse hyperbolic trigonometric functions.\nnp.sqrt Square root.\nnp.exp Exponential.\nnp.log, np.log2, np.log10 Logarithms of base e, 2, and 10, respectively.\n'

In [47]:
x = np.linspace(-1, 1, 11)
x

array([-1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8,  1. ])

In [48]:
y = np.sin(np.pi * x)
np.round(y, decimals=4)


array([-0.    , -0.5878, -0.9511, -0.9511, -0.5878,  0.    ,  0.5878,
        0.9511,  0.9511,  0.5878,  0.    ])

In [49]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
np.sin(x) ** 2 + np.cos(x) ** 2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
"""
NumPy function Description
np.cos, np.sin, np.tan Trigonometric functions.
np.arccos, np.arcsin. np.arctan Inverse trigonometric functions.
np.cosh, np.sinh, np.tanh Hyperbolic trigonometric functions.
np.arccosh, np.arcsinh, np.arctanh Inverse hyperbolic trigonometric functions.
np.sqrt Square root.
np.exp Exponential.
np.log, np.log2, np.log10 Logarithms of base e, 2, and 10, respectively.

"""

'\nNumPy function Description\nnp.cos, np.sin, np.tan Trigonometric functions.\nnp.arccos, np.arcsin. np.arctan Inverse trigonometric functions.\nnp.cosh, np.sinh, np.tanh Hyperbolic trigonometric functions.\nnp.arccosh, np.arcsinh, np.arctanh Inverse hyperbolic trigonometric functions.\nnp.sqrt Square root.\nnp.exp Exponential.\nnp.log, np.log2, np.log10 Logarithms of base e, 2, and 10, respectively.\n\n'

In [52]:
"""
np.add, np.subtract, 
np.multiply, np.divide
Addition, subtraction, multiplication and division of two NumPy arrays.
np.power Raise first input argument to the power of the second input argument 
(applied elementwise).
np.remainder The remainder of division.
np.reciprocal The reciprocal (inverse) of each element.
np.real, np.imag, np.conj The real part, imaginary part, and the complex conjugate of the 
elements in the input arrays.
np.sign, np.abs The sign and the absolute value.
np.floor, np.ceil, np.rint Convert to integer values.
np.round Round to a given number of decimals.
"""

'\nnp.add, np.subtract, \nnp.multiply, np.divide\nAddition, subtraction, multiplication and division of two NumPy arrays.\nnp.power Raise first input argument to the power of the second input argument \n(applied elementwise).\nnp.remainder The remainder of division.\nnp.reciprocal The reciprocal (inverse) of each element.\nnp.real, np.imag, np.conj The real part, imaginary part, and the complex conjugate of the \nelements in the input arrays.\nnp.sign, np.abs The sign and the absolute value.\nnp.floor, np.ceil, np.rint Convert to integer values.\nnp.round Round to a given number of decimals.\n'

# np.vectorize

Occasionally it is necessary to define new functions that operate on NumPy arrays on an 
element-by-element basis. A good way to implement such functions is to express it in terms of already 
existing NumPy operators and expressions, but in cases when this is not possible, the np.vectorize function 
can be a convenient tool. This function takes a non-vectorized function and returns a vectorized function. 
For example, consider the following implementation of the Heaviside step function, which works for 
scalar input:

In [53]:
def heaviside(x):
    return 1 if x > 0 else 0

heaviside(-1)

0

In [54]:
 heaviside(1.5)

1

In [56]:
# The above function works for scalar input, what about an array input ???

In [62]:
x = np.linspace(-5, 5, 11)

# Value Error
# heaviside(x)

In [58]:
heaviside = np.vectorize(heaviside)
heaviside(x)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [63]:
def another_heaviside(x):
    return 1.0 * (x > 0)

another_heaviside(x)

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.])

# Aggregate Functions

In [64]:
"""
NumPy provides another set of functions for calculating aggregates for NumPy arrays, which take an array as 
input and by default return a scalar as output. For example, statistics such as averages, standard deviations, 
and variances of the values in the input array, and functions for calculating the sum and the product of 
elements in an array, are all aggregate functions.


"""

'\nNumPy provides another set of functions for calculating aggregates for NumPy arrays, which take an array as \ninput and by default return a scalar as output. For example, statistics such as averages, standard deviations, \nand variances of the values in the input array, and functions for calculating the sum and the product of \nelements in an array, are all aggregate functions.\n\n\n'

In [65]:
data = np.random.normal(size=(15, 15))
np.mean(data)
data.mean()

-0.05268795440367581

In [66]:
"""
np.mean The average of all values in the array.
np.std Standard deviation.
np.var Variance.
np.sum Sum of all elements.
np.prod Product of all elements.
np.cumsum Cumulative sum of all elements.
np.cumprod Cumulative product of all elements.
np.min, np.max The minimum / maximum value in an array.
np.argmin, np.argmax The index of the minimum / maximum value in an array.
np.all Return True if all elements in the argument array are nonzero.
np.any Return True if any of the elements in the argument array is nonzero.

"""

'\nnp.mean The average of all values in the array.\nnp.std Standard deviation.\nnp.var Variance.\nnp.sum Sum of all elements.\nnp.prod Product of all elements.\nnp.cumsum Cumulative sum of all elements.\nnp.cumprod Cumulative product of all elements.\nnp.min, np.max The minimum / maximum value in an array.\nnp.argmin, np.argmax The index of the minimum / maximum value in an array.\nnp.all Return True if all elements in the argument array are nonzero.\nnp.any Return True if any of the elements in the argument array is nonzero.\n\n'

In [67]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

(10, 15)

In [68]:
data.sum(axis=(0, 2)).shape

data.sum()

-48.217029168179174

In [69]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [70]:
data.sum()

data.sum(axis=0)

data.sum(axis=1)

array([ 6, 15, 24])

# Boolean Arrays and Conditional Expressions

In [71]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a < b

array([ True,  True, False, False])

In [72]:
np.all(a < b)

False

In [73]:
 np.any(a < b)

True

In [75]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
    
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding elemment in b")
        
else:
    print("All elements in b are smaller than their corresponding element in a")

Some elements in a are smaller than their corresponding elemment in b


In [76]:
"""
The advantage of Boolean-valued arrays, however, is that they often make it possible to avoid 
conditional if statements altogether. By using Boolean-valued arrays in arithmetic expressions, it is possible 
to write conditional computations in vectorized form. When appearing in an arithmetic expression together 
with a scalar number, or another NumPy array with a numerical data type, a Boolean array is converted to a 
numerical-valued array with values 0 and 1 in place of False and True, respectively.
"""

x = np.array([-2, -1, 0, 1, 2])
x > 0

array([False, False, False,  True,  True])

In [77]:
1 * (x > 0)

array([0, 0, 0, 1, 1])

In [78]:
 x * (x > 0)

array([0, 0, 0, 1, 2])