Summary: 

This notebook is  a brief introduction to array-based programming with the NumPy library which is a core library for computing  with Python that provides a foundation for nearly all computational libraries for Python. Familiarity with  the NumPy library and its usage patterns is a fundamental skill for using Python for scientific and technical  computing. Here we started with introducing NumPy’s data structure for n-dimensional arrays – the ndarray object – and we continued by discussing functions for creating and manipulating arrays, including indexing and slicing for extracting elements from arrays. We also discussed functions and operators for performing computations with ndarray objects, with an emphasis on vectorized expressions and operators for efficient computation with arrays.

In [18]:
2*2

4

In [19]:
"""
from ast import In
In[1]
"""

'\nfrom ast import In\nIn[1]\n'

In [20]:
from doctest import OutputChecker


# OutputChecker[1]

In [21]:
# In

In [22]:
from numpy import outer


outer

<function numpy.outer(a, b, out=None)>

In [23]:
1 + 2

3

In [24]:
x = 1 ; # Output blocked by ;

In [25]:
2

2

In [26]:
# import os : Autocompletion and Object Introspection

In [27]:
import math 
# math.cos.help() 

In [28]:
# File navigation 
# !dir (Windows)
# !ls (Unix)

In [29]:
def fib(n):
    
     """
     Return a list of the first n Fibonacci numbers.
     """
        
     f0 , f1 = 0 , 1
     f = [1] * n
        
     for i in range(1, n):
         f[i] = f0 + f1
         f0, f1 = f1, f[i]
        
     return f

print(fib(10))

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]


In [ ]:
# Debugger
# fib(1.0)

In [31]:
# %debug

> c:\users\golam\appdata\local\temp\ipykernel_14468\1422583367.py(5)<module>()



In [ ]:
# %reset

"""
The %reset command provides this 
functionality (use the flag –f to force the reset). Using this command can often eliminate the need for 
otherwise common exit–restart cycles of the console. Although it is necessary to reimport modules after 
the %reset command has been used, it is important to known that even if the modules have changed since 
the last import, a new import after a %reset will not import the new module but rather reenable a cached 
version of the module from the previous import. When developing Python modules, this is usually not the 
desired behavior. In that case, a reimport of a previously imported (and since updated) module, can often be 
achieved by using the dreload function.

"""

'\nThe %reset command provides this \nfunctionality (use the flag –f to force the reset). Using this command can often eliminate the need for \notherwise common exit–restart cycles of the console. Although it is necessary to reimport modules after \nthe %reset command has been used, it is important to known that even if the modules have changed since \nthe last import, a new import after a %reset will not import the new module but rather reenable a cached \nversion of the module from the previous import. When developing Python modules, this is usually not the \ndesired behavior. In that case, a reimport of a previously imported (and since updated) module, can often be \nachieved by using the dreload function.\n\n'

In [ ]:
# %timeit fib(100)

In [ ]:
#  %time result = fib(100)

In [ ]:
import numpy as np
def random_walker_max_distance(M, N):
    """
     Simulate N random walkers taking M steps, and return the largest distance
     from the starting point achieved by any of the random walkers.
     """
    trajectories = [np.random.randn(M).cumsum() for _ in range(N)]
    return np.max(np.abs(trajectories))

In [ ]:
%prun random_walker_max_distance(400, 10000)

         20013 function calls in 0.308 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    10000    0.166    0.000    0.166    0.000 {method 'randn' of 'numpy.random.mtrand.RandomState' objects}
    10000    0.065    0.000    0.065    0.000 {method 'cumsum' of 'numpy.ndarray' objects}
        1    0.046    0.046    0.298    0.298 2905491560.py:2(random_walker_max_distance)
        1    0.010    0.010    0.241    0.241 2905491560.py:7(<listcomp>)
        1    0.010    0.010    0.307    0.307 <string>:1(<module>)
        1    0.010    0.010    0.010    0.010 {method 'reduce' of 'numpy.ufunc' objects}
        1    0.000    0.000    0.308    0.308 {built-in method builtins.exec}
        1    0.000    0.000    0.010    0.010 fromnumeric.py:69(_wrapreduction)
        1    0.000    0.000    0.010    0.010 <__array_function__ internals>:177(amax)
        1    0.000    0.000    0.010    0.010 fromnumeric.py:2677(amax)
        1    0

# 1. The numpy Array Object

In [ ]:
# The numpy array object

import numpy as np
data = np.array([[1, 2], [3, 4], [5, 6]])
type(data)

numpy.ndarray

In [ ]:
"""
shape A tuple that contains the number of elements (i.e., the length) for each dimension (axis) 
of the array.
size The total number of elements in the array.
ndim Number of dimensions (axes).
nbytes Number of bytes used to store the data.
dtype The data type of the elements in the array
"""

'\nshape A tuple that contains the number of elements (i.e., the length) for each dimension (axis) \nof the array.\nsize The total number of elements in the array.\nndim Number of dimensions (axes).\nnbytes Number of bytes used to store the data.\ndtype The data type of the elements in the array\n'

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.ndim

2

In [ ]:
data.shape

(3, 2)

In [ ]:
data.size

6

In [ ]:
data.size

6

In [ ]:
data.nbytes

24

In [ ]:
"""
int int8, int16, int32, int64 Integers.
uint uint8, uint16, uint32, uint64 Unsigned (non-negative) integers.
bool bool Boolean (True or False).
float float16, float32, float64, float128 Floating-point numbers.
complex complex64, complex128, complex256 Complex-valued floating-point numbers.
"""

'\nint int8, int16, int32, int64 Integers.\nuint uint8, uint16, uint32, uint64 Unsigned (non-negative) integers.\nbool bool Boolean (True or False).\nfloat float16, float32, float64, float128 Floating-point numbers.\ncomplex complex64, complex128, complex256 Complex-valued floating-point numbers.\n'

In [ ]:
# Data Types

In [ ]:
data = np.array([1, 2, 3], dtype=float)
data

array([1., 2., 3.])

In [ ]:
data.dtype

dtype('float64')

In [ ]:
# Complex Numbers

In [ ]:
d1 = np.array([1, 2, 3], dtype=float)
d2 = np.array([1, 2, 3], dtype=complex)
d1 + d2

array([2.+0.j, 4.+0.j, 6.+0.j])

In [ ]:
(d1 + d2).dtype

dtype('complex128')

In [ ]:
data = np.array([1, 2, 3], dtype=complex)
print("Data : ",data)
print("Real Part : ",data.real)
print("Imaginary Part : ",data.imag)

Data :  [1.+0.j 2.+0.j 3.+0.j]
Real Part :  [1. 2. 3.]
Imaginary Part :  [0. 0. 0.]


# Creating Arrays

In [ ]:
np.array([1, 2, 3, 4])
data.ndim

1

In [ ]:
new_array = np.array([[1, 2], [3, 4]])

In [ ]:
new_array.ndim

2

In [ ]:
new_array.shape

(2, 2)

In [ ]:
np.arange(0.0, 10, 1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.logspace(0, 2, 5) 

array([  1.        ,   3.16227766,  10.        ,  31.6227766 ,
       100.        ])

In [ ]:
# Meshgrid Arrays
x = np.array([-1, 0, 1])
y = np.array([-2, 0, 2])
X,Y = np.meshgrid(x, y)

In [ ]:
X

array([[-1,  0,  1],
       [-1,  0,  1],
       [-1,  0,  1]])

In [ ]:
Y

array([[-2, -2, -2],
       [ 0,  0,  0],
       [ 2,  2,  2]])

In [ ]:
Z = (X + Y) ** 2
Z

array([[9, 4, 1],
       [1, 0, 1],
       [1, 4, 9]])

In [ ]:
# Creating Uninitialized Arrays
np.empty(3, dtype=np.float)

C:\Users\golam\AppData\Local\Temp\ipykernel_30616\3813404062.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.empty(3, dtype=np.float)


array([0., 0., 0.])

In [ ]:
# Creating Arrays with Properties of Other Arrays

def f(x):
    
     y = np.ones_like(x)
     # compute with x and y
    
     return y
    
"""
At the first line of the body of this function, a new array y is created using np.ones_like, which results 
in an array of the same size and data type as x, and filled with ones.

"""


'\nAt the first line of the body of this function, a new array y is created using np.ones_like, which results \nin an array of the same size and data type as x, and filled with ones.\n\n'

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(3, k=1)


array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [ ]:
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [ ]:
np.diag(np.arange(0, 20, 5))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

# 3. Indexing and Slicing

In [ ]:
"""
a[m] Select element at index m, where m is an integer (start counting form 0).
a[-m] Select the mth element from the end of the list, where m is an integer. The last 
element in the list is addressed as -1, the second-to-last element as -2, and so on.
a[m:n] Select elements with index starting at m and ending at n −1 (m and n are integers).
a[:] or a[0:-1] Select all elements in the given axis.
a[:n] Select elements starting with index 0 and going up to index n −1 (integer).
a[m:] or a[m:-1] Select elements starting with index m (integer) and going up to the last element in 
the array.
a[m:n:p] Select elements with index m through n (exclusive), with increment p.
a[::-1] Select all the elements, in reverse order

"""

'\na[m] Select element at index m, where m is an integer (start counting form 0).\na[-m] Select the mth element from the end of the list, where m is an integer. The last \nelement in the list is addressed as -1, the second-to-last element as -2, and so on.\na[m:n] Select elements with index starting at m and ending at n −1 (m and n are integers).\na[:] or a[0:-1] Select all elements in the given axis.\na[:n] Select elements starting with index 0 and going up to index n −1 (integer).\na[m:] or a[m:-1] Select elements starting with index m (integer) and going up to the last element in \nthe array.\na[m:n:p] Select elements with index m through n (exclusive), with increment p.\na[::-1] Select all the elements, in reverse order\n\n'

In [ ]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B = A[A > 5]
B

array([6, 7, 8, 9])

In [ ]:
B[0] = -1 # this does not affect A
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
B

array([-1,  7,  8,  9])

In [ ]:
A[A > 5] = -1
A

array([ 0,  1,  2,  3,  4,  5, -1, -1, -1, -1])

In [ ]:
# Reshaping and Resizing

In [ ]:
data = np.array([[1, 2], [3, 4]])

In [ ]:
np.reshape(data, (1, 4))

array([[1, 2, 3, 4]])

In [ ]:
data.reshape(4)

array([1, 2, 3, 4])

In [ ]:
# Multidimensional Arrays

In [ ]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
A.shape

(6, 6)

In [ ]:
A.ndim

2

In [ ]:
A.size

36

In [ ]:
A[:, 1] # the second column

array([ 1, 11, 21, 31, 41, 51])

In [ ]:
A[1, :] # the second row

array([10, 11, 12, 13, 14, 15])

In [ ]:
A[:3, :3] # upper half diagonal block matrix

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [ ]:
A[3:, :3] # lower left off-diagonal block matrix

array([[30, 31, 32],
       [40, 41, 42],
       [50, 51, 52]])

In [ ]:
A[::2, ::2] # every second element starting from 0, 0

array([[ 0,  2,  4],
       [20, 22, 24],
       [40, 42, 44]])

In [ ]:
A[1::2, 1::3] # every second and third element starting from 1, 1

array([[11, 14],
       [31, 34],
       [51, 54]])

In [ ]:
# View and Copy while slicing

In [ ]:
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
B = A[1:5, 1:5]
B

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34],
       [41, 42, 43, 44]])

In [ ]:
A

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
import numpy as np
f = lambda m, n: n + 10 * m
A = np.fromfunction(f, (6, 6), dtype=int)
B = A[1:5, 1:5]
B[:, :] = 0 # Changing B changes A
B   

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:

"""
Here, assigning new values to the elements in an array B, which is created from the array A, also 
modifies the values in A (since both arrays refer to the same data in the memory). The fact that extracting 
subarrays results in views rather than new independent arrays eliminates the need for copying data and 
improves performance. When a copy rather than a view is needed, the view can be copied explicitly by using 
the copy method of the ndarray instance
"""
A # A is changed as B has been changed

array([[ 0,  1,  2,  3,  4,  5],
       [10,  0,  0,  0,  0, 15],
       [20,  0,  0,  0,  0, 25],
       [30,  0,  0,  0,  0, 35],
       [40,  0,  0,  0,  0, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
# copy

In [ ]:
C = B[1:3, 1:3].copy()

In [ ]:
C

array([[0, 0],
       [0, 0]])

In [ ]:
C[:, :] = 1 # this does not affect B since C is a copy of the view B[1:3, 1:3]

In [ ]:
C

array([[1, 1],
       [1, 1]])

In [ ]:
"""
In addition to the copy attribute of the ndarray class, an array can also be copied using the function 
np.copy, or, equivalently, using the np.array function with the keyword argument copy=True
"""

B

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
A = np.linspace(0, 1, 11) 
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [ ]:
A[[0, 2, 4]] # The same thing can be accomplished by indexing with a Python list

array([0. , 0.2, 0.4])

In [ ]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
# Fancy Indexing and Boolean-valued Indexin

In [ ]:
A = np.linspace(0, 1, 11)
A

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A[np.array([0, 2, 4])]

array([0. , 0.2, 0.4])

In [ ]:
A[[0, 2, 4]] # The same thing can be accomplished by indexing with a Python list

array([0. , 0.2, 0.4])

In [ ]:
A > 0.5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [ ]:
A[A > 0.5]

array([0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
indices = [2, 4, 6]
B = A[indices]
print("Inital value of B", B)
B[0] = -1 # this does not affect A
print("Final value of B : ", B)
A

Inital value of B [2 4 6]
Final value of B :  [-1  4  6]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
A[indices] = -1
A # now A is changed

array([ 0,  1, -1,  3, -1,  5, -1,  7,  8,  9])

In [ ]:
A = np.arange(10)
print("A:", A)
B = A[A > 5]
B[0] = -1 # this does not affect A
A

A: [0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Reshaping and Resizing

In [ ]:
import numpy as np

data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [ ]:
data.ndim

2

In [ ]:
data.shape

(2, 2)

In [ ]:
a = np.reshape(data, (1, 4)) # reshaping . note that it's view, not copy. changing a will change data
a

array([[1, 2, 3, 4]])

In [ ]:
data.reshape(4) # second reshaping

array([1, 2, 3, 4])

In [ ]:
data # original data is same even after reshaping and saving the value inside a

array([[1, 2],
       [3, 4]])

Broadcasting

In [ ]:
import numpy as np
# Let's create an array using arange()
array_1d = np.arange(0, 10)
print("Original Array : ", array_1d)
array_1d[0:5] = 500
print("After Broadcasting : ", array_1d)

Original Array :  [0 1 2 3 4 5 6 7 8 9]
After Broadcasting :  [500 500 500 500 500   5   6   7   8   9]


In [ ]:
import numpy as np
# Lets create a 2D martix with ones
array_2d = np.ones((4, 4))

print("2D Array")
print(array_2d)

# Lets broadcast 300 to the first row of array_2d
array_2d[0] = 300
print("\n After Broadcasting")
print(array_2d)


2D Array
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 After Broadcasting
[[300. 300. 300. 300.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]
 [  1.   1.   1.   1.]]


Ravel and Flatten

In [ ]:
data = np.array([[1, 2], [3, 4]])
data

array([[1, 2],
       [3, 4]])

In [ ]:
data.shape

(2, 2)

In [ ]:
data.flatten()

array([1, 2, 3, 4])

In [ ]:
data.flatten().shape

(4,)

In [ ]:
# new axis
import numpy as np
data = np.arange(0, 5)
data

array([0, 1, 2, 3, 4])

In [ ]:
data.shape

(5,)

In [ ]:
column = data[:, np.newaxis]
column

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
column.shape

(5, 1)

In [ ]:
column.ndim

2

In [ ]:
row = data[np.newaxis, :]
row

array([[0, 1, 2, 3, 4]])

In [ ]:
row.shape

(1, 5)

In [ ]:
# Stack
data = np.arange(5)
data
np.array([0, 1, 2, 3, 4])
np.vstack((data, data, data))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [ ]:
data = np.arange(5)
data
np.array([0, 1, 2, 3, 4])
np.hstack((data, data, data))

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [ ]:
"""
This indeed stacks the arrays horizontally, but not in the way intended here. To make np.hstack treat 
the input arrays as columns and stack them accordingly, we need to make the input arrays two-dimensional 
arrays of shape (1, 5) rather than one-dimensional arrays of shape (5,). As discussed earlier, we can insert 
a new axis by indexing with np.newaxis:
"""

'\nThis indeed stacks the arrays horizontally, but not in the way intended here. To make np.hstack treat \nthe input arrays as columns and stack them accordingly, we need to make the input arrays two-dimensional \narrays of shape (1, 5) rather than one-dimensional arrays of shape (5,). As discussed earlier, we can insert \na new axis by indexing with np.newaxis:\n'

In [ ]:
data = data[:, np.newaxis]
np.hstack((data, data, data))

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [ ]:
"""
The number of elements in a NumPy array cannot be changed once the array has been created. To 
insert, append, and remove elements from a NumPy array, for example, using the function np.append, 
np.insert, and np.delete, a new array must be created and the data copied to it. It may sometimes be 
tempting to use these functions to grow or shrink the size of a NumPy array, but due to the overhead of 
creating new arrays and copying the data, it is usually a good idea to preallocate arrays with size such that 
they do not later need to be resized.
"""

'\nThe number of elements in a NumPy array cannot be changed once the array has been created. To \ninsert, append, and remove elements from a NumPy array, for example, using the function np.append, \nnp.insert, and np.delete, a new array must be created and the data copied to it. It may sometimes be \ntempting to use these functions to grow or shrink the size of a NumPy array, but due to the overhead of \ncreating new arrays and copying the data, it is usually a good idea to preallocate arrays with size such that \nthey do not later need to be resized.\n'

# 5. Vectorized Expressions

In [ ]:
"""
NumPy implements functions and vectorized 
operations corresponding to most fundamental mathematical functions and operators. 
"""

'\nNumPy implements functions and vectorized \noperations corresponding to most fundamental mathematical functions and operators. \n'

In [ ]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
y = np.array([[5, 6], [7, 8]])
y

array([[5, 6],
       [7, 8]])

Arithmetic Operations

In [ ]:
x + y

array([[ 6,  8],
       [10, 12]])

In [ ]:
y - x

array([[4, 4],
       [4, 4]])

In [ ]:
x*y

array([[ 5, 12],
       [21, 32]])

In [ ]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [ ]:
2*x

array([[2, 4],
       [6, 8]])

In [ ]:
2**x

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [ ]:
import numpy as np
x = np.array([1, 2, 3, 4]).reshape(2, 2)
z = np.array([1, 2, 3, 4])
# error : problem with shape
# x / z

In [ ]:
"""
The two expressions have the same effect, but in the first case x is reassigned to a new array, while in the 
second case the values of array x are updated in place. Extensive use of in-place operators tends to impair 
code readability, and in-place operators should therefore be used only when necessary.
"""


'\nThe two expressions have the same effect, but in the first case x is reassigned to a new array, while in the \nsecond case the values of array x are updated in place. Extensive use of in-place operators tends to impair \ncode readability, and in-place operators should therefore be used only when necessary.\n'

In [ ]:
x = np.arange(5)
y = np.arange(5)

x += y
x

In [ ]:
x = np.arange(5)
y = np.arange(5)

z = x + y
z

Elementwise Functions

In [ ]:
"""
np.cos, np.sin, np.tan Trigonometric functions.
np.arccos, np.arcsin. np.arctan Inverse trigonometric functions.
np.cosh, np.sinh, np.tanh Hyperbolic trigonometric functions.
np.arccosh, np.arcsinh, np.arctanh Inverse hyperbolic trigonometric functions.
np.sqrt Square root.
np.exp Exponential.
np.log, np.log2, np.log10 Logarithms of base e, 2, and 10, respectively.
"""


In [ ]:
x = np.linspace(-1, 1, 11)
x

In [ ]:
y = np.sin(np.pi * x)
np.round(y, decimals=4)


In [ ]:
np.add(np.sin(x) ** 2, np.cos(x) ** 2)

In [ ]:
np.sin(x) ** 2 + np.cos(x) ** 2

In [ ]:
"""
NumPy function Description
np.cos, np.sin, np.tan Trigonometric functions.
np.arccos, np.arcsin. np.arctan Inverse trigonometric functions.
np.cosh, np.sinh, np.tanh Hyperbolic trigonometric functions.
np.arccosh, np.arcsinh, np.arctanh Inverse hyperbolic trigonometric functions.
np.sqrt Square root.
np.exp Exponential.
np.log, np.log2, np.log10 Logarithms of base e, 2, and 10, respectively.

"""

In [ ]:
"""
np.add, np.subtract, 
np.multiply, np.divide
Addition, subtraction, multiplication and division of two NumPy arrays.
np.power Raise first input argument to the power of the second input argument 
(applied elementwise).
np.remainder The remainder of division.
np.reciprocal The reciprocal (inverse) of each element.
np.real, np.imag, np.conj The real part, imaginary part, and the complex conjugate of the 
elements in the input arrays.
np.sign, np.abs The sign and the absolute value.
np.floor, np.ceil, np.rint Convert to integer values.
np.round Round to a given number of decimals.
"""

# np.vectorize

Occasionally it is necessary to define new functions that operate on NumPy arrays on an 
element-by-element basis. A good way to implement such functions is to express it in terms of already 
existing NumPy operators and expressions, but in cases when this is not possible, the np.vectorize function 
can be a convenient tool. This function takes a non-vectorized function and returns a vectorized function. 
For example, consider the following implementation of the Heaviside step function, which works for 
scalar input:

In [ ]:
def heaviside(x):
    return 1 if x > 0 else 0

heaviside(-1)

In [ ]:
heaviside(1.5)

In [ ]:
# The above function works for scalar input, what about an array input ???

In [ ]:
x = np.linspace(-5, 5, 11)

# Value Error
# heaviside(x)

In [ ]:
heaviside = np.vectorize(heaviside)
heaviside(x)

In [ ]:
def another_heaviside(x):
    return 1.0 * (x > 0)

another_heaviside(x)

# Aggregate Functions

In [ ]:
"""
NumPy provides another set of functions for calculating aggregates for NumPy arrays, which take an array as 
input and by default return a scalar as output. For example, statistics such as averages, standard deviations, 
and variances of the values in the input array, and functions for calculating the sum and the product of 
elements in an array, are all aggregate functions.


"""

In [ ]:
data = np.random.normal(size=(15, 15))
np.mean(data)
data.mean()

In [ ]:
"""
np.mean The average of all values in the array.
np.std Standard deviation.
np.var Variance.
np.sum Sum of all elements.
np.prod Product of all elements.
np.cumsum Cumulative sum of all elements.
np.cumprod Cumulative product of all elements.
np.min, np.max The minimum / maximum value in an array.
np.argmin, np.argmax The index of the minimum / maximum value in an array.
np.all Return True if all elements in the argument array are nonzero.
np.any Return True if any of the elements in the argument array is nonzero.

"""

In [ ]:
data = np.random.normal(size=(5, 10, 15))
data.sum(axis=0).shape

In [ ]:
data.sum(axis=(0, 2)).shape

data.sum()

In [ ]:
data = np.arange(1,10).reshape(3,3)
data

In [ ]:
data.sum()

data.sum(axis=0)

data.sum(axis=1)

# Boolean Arrays and Conditional Expressions

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a < b

array([ True,  True, False, False])

In [ ]:
np.all(a < b)

False

In [ ]:
import numpy as np
np.any(a < b)

True

In [ ]:
if np.all(a < b):
    print("All elements in a are smaller than their corresponding element in b")
    
elif np.any(a < b):
    print("Some elements in a are smaller than their corresponding element in b")
        
else:
    print("All elements in b are smaller than their corresponding element in a")

In [ ]:
"""
The advantage of Boolean-valued arrays, however, is that they often make it possible to avoid 
conditional if statements altogether. By using Boolean-valued arrays in arithmetic expressions, it is possible 
to write conditional computations in vectorized form. When appearing in an arithmetic expression together 
with a scalar number, or another NumPy array with a numerical data type, a Boolean array is converted to a 
numerical-valued array with values 0 and 1 in place of False and True, respectively.
"""

x = np.array([-2, -1, 0, 1, 2])
x > 0

array([False, False, False,  True,  True])

In [ ]:
1 * (x > 0)

In [ ]:
x * (x > 0)

array([0, 0, 0, 1, 2])

In [ ]:
import numpy as np 

def pulse(x, position, height, width):
    return height * (x >= position) * (x <= (position + width))

x = np.linspace(-5, 5, 11)
pulse(x, position=-2, height=1, width=5)

array([0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0])

In [ ]:
pulse(x, position=1, height=1, width=5)

array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [ ]:
x = np.linspace(-4, 4, 9)
np.where(x < 0, x**2, x**3)

In [ ]:
np.select([x < -1, x < 2, x >= 2],
    [x**2 , x**3 , x**4])

array([ 25.,  16.,   9.,   4.,  -1.,   0.,   1.,  16.,  81., 256., 625.])

In [ ]:
import numpy as np
# np.choose([0, 0, 0, 1, 1, 1, 2, 2, 2],[x**2, x**3, x**4])

In [ ]:
np.nonzero(abs(x) > 2)

x[np.nonzero(abs(x) > 2)]

x[abs(x) > 2]


array([-5., -4., -3.,  3.,  4.,  5.])

# NumPy functions for conditional and logical expressions

In [ ]:
"""
np.where Choose values from two arrays depending on the value of a 
condition array.
np.choose Choose values from a list of arrays depending on the values of a 
given index array.
np.select Choose values from a list of arrays depending on a list of conditions.
np.nonzero Return an array with indices of nonzero elements.
np.logical_and Perform and elementwise AND operation.
np.logical_or, np.logical_xor Elementwise OR/XOR operations.
np.logical_not Elementwise NOT operation (inverting).
"""

'\nnp.where Choose values from two arrays depending on the value of a \ncondition array.\nnp.choose Choose values from a list of arrays depending on the values of a \ngiven index array.\nnp.select Choose values from a list of arrays depending on a list of conditions.\nnp.nonzero Return an array with indices of nonzero elements.\nnp.logical_and Perform and elementwise AND operation.\nnp.logical_or, np.logical_xor Elementwise OR/XOR operations.\nnp.logical_not Elementwise NOT operation (inverting).\n'

Set

In [ ]:
a = np.unique([1, 2, 3, 3])
b = np.unique([2, 3, 4, 4, 5, 6, 5])
np.in1d(a, b)

array([False,  True,  True])

In [ ]:
1 in a

True

In [ ]:
1 in b

False

In [ ]:
# To test if a is a subset of b
np.all(np.in1d(a, b))


In [ ]:
np.union1d(a, b)

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.intersect1d(a, b)

array([2, 3])

In [ ]:
np.setdiff1d(a, b)

array([1])

In [ ]:
"""
np.unique Create a new array with unique elements, where each value only appears once.
np.in1d Test for the existence of an array of elements in another array.
np.intersect1d Return an array with elements that are contained in two given arrays.
np.setdiff1d Return an array with elements that are contained in one but not the other, of two given arrays.
np.union1d Return an array with elements that are contained in either, or both, of two given arrays.
"""

In [ ]:
data = np.arange(9).reshape(3, 3)
data

In [ ]:
data = np.random.randn(1, 2, 3, 4, 5)
data.shape

In [ ]:
data.T.shape

In [ ]:
"""
np.transpose,
np.ndarray.transpose, np.ndarray.T
The transpose (reverse axes) of an array.
np.fliplr / np.flipud Reverse the elements in each row / column.
np.rot90 Rotate the elements along the first two axes by 90 degrees.
np.sort,
np.ndarray.sort
Sort the element of an array along a given specified axis (which 
default to the last axis of the array). The np.ndarray method sort 
performs the sorting in place, modifying the input array.
"""

# Matrix and Vector Operations

In [ ]:
"""
In NumPy, the * operator is used for elementwise multiplication. For two two-dimensional arrays A and B, 
the expression A * B therefore does not compute a matrix product (in contrast to many other computing 
environments). Currently there is no operator for denoting matrix multiplication,4
 and instead the NumPy 
function np.dot is used for this purpose. 
"""

'\nIn NumPy, the * operator is used for elementwise multiplication. For two two-dimensional arrays A and B, \nthe expression A * B therefore does not compute a matrix product (in contrast to many other computing \nenvironments). Currently there is no operator for denoting matrix multiplication,4\n and instead the NumPy \nfunction np.dot is used for this purpose. \n'

In [ ]:
"""
np.dot Matrix multiplication (dot product) between two given arrays representing vectors, 
arrays, or tensors.
np.inner Scalar multiplication (inner product) between two arrays representing vectors.
np.cross The cross product between two arrays that represent vectors.
np.tensordot Dot product along specified axes of multidimensional arrays.
np.outer Outer product (tensor product of vectors) between two arrays representing vectors.
np.kron Kronecker product (tensor product of matrices) between arrays representing 
matrices and higher-dimensional arrays.
np.einsum Evaluates Einstein’s summation convention for multidimensional arrays.
"""

In [ ]:
A = np.arange(1, 7).reshape(2, 3)
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
B = np.arange(1, 7).reshape(3, 2)
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
A = np.arange(9).reshape(3, 3)
A


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x = np.arange(3)
x

array([0, 1, 2])

In [ ]:
np.dot(A, x)

array([ 5, 14, 23])

In [ ]:
A.dot(x)

array([ 5, 14, 23])

In [ ]:
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)
Ap = np.dot(B, np.dot(A, np.linalg.inv(B)))
Ap

array([[ 6.84644087, -3.60327531, -3.35536533],
       [ 8.55041178, -4.79689781, -4.11791569],
       [ 0.94186971,  0.03764807, -0.53800847]])

In [ ]:
Ap = B.dot(A.dot(np.linalg.inv(B)))
Ap

array([[ 6.84644087, -3.60327531, -3.35536533],
       [ 8.55041178, -4.79689781, -4.11791569],
       [ 0.94186971,  0.03764807, -0.53800847]])

In [ ]:
# Readable code with matrix object

In [ ]:
A = np.matrix(A)
B = np.matrix(B)
Ap = B * A * B.I
Ap

In [ ]:
A = np.asmatrix(A)
B = np.asmatrix(B)
Ap = B * A * B.I
Ap

matrix([[ 6.84644087, -3.60327531, -3.35536533],
        [ 8.55041178, -4.79689781, -4.11791569],
        [ 0.94186971,  0.03764807, -0.53800847]])

In [ ]:
np.inner(x, x)

5

In [ ]:
np.dot(x, x)

5

In [ ]:
y = x[:, np.newaxis]
y

array([[0],
       [1],
       [2]])

In [ ]:
np.dot(y.T, y)

array([[5]])

In [ ]:
x = np.array([1, 2, 3])
np.outer(x, x)

In [ ]:
"""
The outer product can also be calculated using the Kronecker product using the function np.kron, 
which, however, in contrast to np.outer, produce an output array of shape (M*P, N*Q) if the input arrays 
have shapes (M, N) and (P, Q), respectively. Thus, for the case of two one-dimensional arrays of length M 
and P, the resulting array has shape (M*P,):
"""

'\nThe outer product can also be calculated using the Kronecker product using the function np.kron, \nwhich, however, in contrast to np.outer, produce an output array of shape (M*P, N*Q) if the input arrays \nhave shapes (M, N) and (P, Q), respectively. Thus, for the case of two one-dimensional arrays of length M \nand P, the resulting array has shape (M*P,):\n'

In [ ]:
np.kron(x, x)

array([0, 0, 0, 0, 1, 2, 0, 2, 4])

In [ ]:
"""
To obtain the result that corresponds to np.outer(x, x), the input array x must be expanded to shape 
(N, 1) and (1, N), in the first and second argument to np.kron, respectively:

"""

np.kron(x[:, np.newaxis], x[np.newaxis, :])

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

In [ ]:
np.kron(np.ones((2,2)), np.identity(2))


array([[1., 0., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.],
       [0., 1., 0., 1.]])

In [ ]:
np.kron(np.identity(2), np.ones((2,2)))


array([[1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [ ]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
np.einsum("n,n", x, y)

70

In [ ]:
np.inner(x, y)

70

In [ ]:
A = np.arange(9).reshape(3, 3)
B = A.T
np.einsum("mk,kn", A, B)

array([[  5,  14,  23],
       [ 14,  50,  86],
       [ 23,  86, 149]])

In [ ]:
np.alltrue(np.einsum("mk,kn", A, B) == np.dot(A, B))

True