In [1]:
# Creating Vectors : 1 D Arrays

In [2]:
import numpy as np

x = np.array([1, 3, 5, 7, 9])
print(x)

[1 3 5 7 9]


In [3]:
import numpy as np

v1 = np.ones(5)
v0 = np.zeros(5)
print(v1)
print(v0)

[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]


In [4]:
import numpy as np

print(np.arange(1, 7))      # Takes default steps of 1 and doesn't include 7
print(np.arange(5))     # Starts at 0 by defualt and ends at 4, giving 5 numbers
print(np.arange(1, 10, 3))      # Starts at 1 and ends at less than 10, 
                                # with a step size of 3

[1 2 3 4 5 6]
[0 1 2 3 4]
[1 4 7]


In [5]:
import numpy as np

print(np.linspace(1, 12, 12)) 
print(np.linspace(1, 12, 5))
print(np.linspace(1, 12, 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
[ 1.    3.75  6.5   9.25 12.  ]
[ 1.   6.5 12. ]


In [6]:
# Creating Multidimensional Arrays

In [8]:
import numpy as np

x = np.ones((3, 4)) # An array with 3 rows and 4 columns
print(x)
print(x.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
2


In [9]:
import numpy as np

x = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])
print(x)

[[4 2 3 2]
 [2 4 3 1]
 [0 4 1 3]]


In [12]:
# Meshgrid

import numpy as np

x = np.arange(0, 5)
y = np.arange(5, 11)

[X, Y] = np.meshgrid(x, y)

print(X) 
print(X.ndim)
print(X.shape)
print("")
print(Y)
print(Y.ndim)
print(Y.shape)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
2
(6, 5)

[[ 5  5  5  5  5]
 [ 6  6  6  6  6]
 [ 7  7  7  7  7]
 [ 8  8  8  8  8]
 [ 9  9  9  9  9]
 [10 10 10 10 10]]
2
(6, 5)


In [13]:
# Reshaping

import numpy as np

x = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])
print(x)
print()
print(np.reshape(x, (2, 6)))  # 2 rows, 6 columns
print()
print(np.reshape(x, (1, 12)))  # 1 row, 12 columns

[[4 2 3 2]
 [2 4 3 1]
 [0 4 1 3]]

[[4 2 3 2 2 4]
 [3 1 0 4 1 3]]

[[4 2 3 2 2 4 3 1 0 4 1 3]]


In [15]:
# Properties of numpy arrays

In [16]:
import numpy as np

v = np.array([1, 5, 9])
M = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])

print("size of v is ", v.size)
print("shape of v is ", v.shape)

print("size of M is ", M.size)
print("shape of M is ", M.shape)

size of v is  3
shape of v is  (3,)
size of M is  12
shape of M is  (3, 4)


In [17]:
import numpy as np

M = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])

print("Bytes per element of M is", M.itemsize)
print("Number of bytes of M are", M.nbytes)
print("Dimensions of M are", M.ndim)
print("Data type of elements in M is", M.dtype)

Bytes per element of M is 4
Number of bytes of M are 48
Dimensions of M are 2
Data type of elements in M is int32


In [19]:
# Indexing Arrays

In [20]:
import numpy as np

v = np.array([1, 5, 9])
print(v[1])

5


In [21]:
import numpy as np

M = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])
print(M[1,2])

3


In [22]:
import numpy as np

M = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])
print(M[1])

[2 4 3 1]


In [23]:
import numpy as np

M = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])
print(M[1,:]) # prints the entire 2nd row
print(M[:,1]) # prints the entire 2nd column

[2 4 3 1]
[2 4 4]


In [24]:
import numpy as np

M = np.array([[4, 2, 3, 2],
              [2, 4, 3, 1],
              [0, 4, 1, 3]])
print(M)
M[2, 3] = 24 #changing element at 3rd row and 4th column
print("--------")
print(M)

[[4 2 3 2]
 [2 4 3 1]
 [0 4 1 3]]
--------
[[ 4  2  3  2]
 [ 2  4  3  1]
 [ 0  4  1 24]]


In [25]:
# Index Slicing

In [26]:
import numpy as np

v = np.array([1, 3, 5, 7, 9, 11])
print(v[2:4]) # 4th element will not be included

[5 7]


In [27]:
import numpy as np

v = np.array([1, 3, 5, 7, 9, 11])
print(v[2::])
print(v[:2:])
print(v[::2])

[ 5  7  9 11]
[1 3]
[1 5 9]


In [49]:
# Slicing Matrices

import numpy as np
M = np.array([[(n + m * 20) for n in range(5)] for m in range(5)])

print(M)
print("------")
print(M[1:4, 1:3]) # slice rows 1, 2 and 3 and columns 1 and 2 

[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]
 [60 61 62 63 64]
 [80 81 82 83 84]]
------
[[21 22]
 [41 42]
 [61 62]]


In [29]:
# Scalar operation

In [30]:
import numpy as np

v = np.arange(1, 11)
print(v) 

print("-----")
print("Using scalar addition")
print(v + 2) # adding 2 to each element in the vector

print("-----")
print("Using scalar subtraction")
print(v - 2) # subtracting 2 from each element in the vector

print("-----")
print("Using scalar multiplication")
print(v * 2) # multiplying each element by 2 in the vector

print("-----")
print("Using scalar division")
print(v / 2) # dividing each element by 2 in the vector

[ 1  2  3  4  5  6  7  8  9 10]
-----
Using scalar addition
[ 3  4  5  6  7  8  9 10 11 12]
-----
Using scalar subtraction
[-1  0  1  2  3  4  5  6  7  8]
-----
Using scalar multiplication
[ 2  4  6  8 10 12 14 16 18 20]
-----
Using scalar division
[0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [31]:
import numpy as np

M = np.array([[(n + m * 20) for n in range(5)] for m in range(5)])
print(M) 

print("-----")
print("Using scalar addition")
print(M + 2) # adding 2 to each element in the matrix

print("-----")
print("Using scalar subtraction")
print(M - 2) # subtracting 2 from each element in the matrix

print("-----")
print("Using scalar multiplication")
print(M * 2) # multiplying each element by 2 in the matrix

print("-----")
print("Using scalar division")
print(M / 2) # dividing each element by 2 in the matrix

[[ 0  1  2  3  4]
 [20 21 22 23 24]
 [40 41 42 43 44]
 [60 61 62 63 64]
 [80 81 82 83 84]]
-----
Using scalar addition
[[ 2  3  4  5  6]
 [22 23 24 25 26]
 [42 43 44 45 46]
 [62 63 64 65 66]
 [82 83 84 85 86]]
-----
Using scalar subtraction
[[-2 -1  0  1  2]
 [18 19 20 21 22]
 [38 39 40 41 42]
 [58 59 60 61 62]
 [78 79 80 81 82]]
-----
Using scalar multiplication
[[  0   2   4   6   8]
 [ 40  42  44  46  48]
 [ 80  82  84  86  88]
 [120 122 124 126 128]
 [160 162 164 166 168]]
-----
Using scalar division
[[ 0.   0.5  1.   1.5  2. ]
 [10.  10.5 11.  11.5 12. ]
 [20.  20.5 21.  21.5 22. ]
 [30.  30.5 31.  31.5 32. ]
 [40.  40.5 41.  41.5 42. ]]


In [32]:
# Elementwise operation

In [33]:
import numpy as np

M = np.array([[(n + m * 5) for n in range(3)] for m in range(3)])
print("M")
print(M) 

N = np.array([[(n * 5) for n in range(3)] for m in range(3)])
print("N")
print(N) 

print("-----")
print("M * M")
print(M * M) # multiplication

print("-----")
print("M + M") # addition
print(M + M)

print("-----")
print("M - N") # subtraction
print(M - N)

print("-----")
print("(M + 1) / (N + 1)")
print((M + 1) / (N + 2)) # division 
                         # to avoid division by zero, we have added scalar 1

M
[[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]
N
[[ 0  5 10]
 [ 0  5 10]
 [ 0  5 10]]
-----
M * M
[[  0   1   4]
 [ 25  36  49]
 [100 121 144]]
-----
M + M
[[ 0  2  4]
 [10 12 14]
 [20 22 24]]
-----
M - N
[[ 0 -4 -8]
 [ 5  1 -3]
 [10  6  2]]
-----
(M + 1) / (N + 1)
[[0.5        0.28571429 0.25      ]
 [3.         1.         0.66666667]
 [5.5        1.71428571 1.08333333]]


In [34]:
import numpy as np

M = np.array([[(n + m * 5) for n in range(4)] for m in range(5)])
print("M")
print(M)        # 5 rows and 4 columns

N = np.array([1, 2, 3, 4])
print("N")
print(N)        # 1 row and 4 columns

print("-----")
print("N * M")
print(N * M)

M
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]
N
[1 2 3 4]
-----
N * M
[[ 0  2  6 12]
 [ 5 12 21 32]
 [10 22 36 52]
 [15 32 51 72]
 [20 42 66 92]]


In [35]:
import numpy as np

M = np.array([[(n + m * 5) for n in range(4)] for m in range(5)])
print("M")
print(M) 

N = np.array([[1], [2], [3], [4], [5]])
print("N")
print(N)

print("-----")
print("N * M")
print(N * M)

M
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]
N
[[1]
 [2]
 [3]
 [4]
 [5]]
-----
N * M
[[  0   1   2   3]
 [ 10  12  14  16]
 [ 30  33  36  39]
 [ 60  64  68  72]
 [100 105 110 115]]


In [40]:
# Data processing tools in NumPy arrays

In [36]:
import numpy as np

current = np.array([2.2, 2.5, 2.5, 2.7, 2.1, 2.5, 2.6, 2.5, 3.0, 2.9, 2.3, 2.8])
print("mean", np.mean(current))     # to calculate mean
print("standard deviation", np.std(current))    # to calculate standard deviation
print("variance", np.var(current))      # to calculate variance

mean 2.5500000000000003
standard deviation 0.25980762113533157
variance 0.06749999999999998


In [37]:
import numpy as np

current = np.array([2.2, 2.5, 2.5, 2.7, 2.1, 2.5, 2.6, 2.5, 3.0, 2.9, 2.3, 2.8])
print("maximum value:", np.max(current))     # to calculate maximum value

maximum value: 3.0


In [38]:
import numpy as np

arr = np.array([1+3j, 2+5j, 3+1j, 8-2j])
print("Real part of arr =", arr.real)
print("Imaginary part of arr = ", arr.imag)

Real part of arr = [1. 2. 3. 8.]
Imaginary part of arr =  [ 3.  5.  1. -2.]


In [39]:
import numpy as np

v = np.arange(1, 10)

print("Sum:", np.sum(v))
print("Product:", np.prod(v))
print("Cumulative Sum:", np.cumsum(v))
print("Cumulative Product:", np.cumprod(v))

Sum: 45
Product: 362880
Cumulative Sum: [ 1  3  6 10 15 21 28 36 45]
Cumulative Product: [     1      2      6     24    120    720   5040  40320 362880]


In [41]:
# Using Conditions on Arrays

In [42]:
a = np.arange(10)
print('the total array:', a)
print("array of booleans:", a < 5)
print('values less than 5:', a[a < 5])

the total array: [0 1 2 3 4 5 6 7 8 9]
array of booleans: [ True  True  True  True  True False False False False False]
values less than 5: [0 1 2 3 4]


In [43]:
import numpy as np

a = np.arange(10)
print(a)
a[a < 5] = 666
print(a)

[0 1 2 3 4 5 6 7 8 9]
[666 666 666 666 666   5   6   7   8   9]


In [44]:
import numpy as np

a = np.arange(20)
print(a)
a[(a > 5) & (a < 10)] = 666
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[  0   1   2   3   4   5 666 666 666 666  10  11  12  13  14  15  16  17
  18  19]


In [45]:
import numpy as np

a = np.arange(20)
print(a)
a[(a > 5) | (a < 10)] = 666
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666 666
 666 666]


In [46]:
# any() and all()
import numpy as np

v = np.linspace(-5, 5, 5)
print(v)

if (v > 0).any():
  print("At leat one element is positive.")
else:
   print("No element is positive.") 

if (v > 0).all():
  print("All elements are postive.")
else:
   print("Not all elements are positive.") 

[-5.  -2.5  0.   2.5  5. ]
At leat one element is positive.
Not all elements are positive.


In [47]:
# iterating elements in array

import numpy as np 

v = np.array([1, 2, 3, 4])
for x in v:
  print(x)

1
2
3
4


In [48]:
import numpy as np 

M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in M:
  for y in x:
    print(y)

1
2
3
4
5
6
7
8


In [50]:
# Vectorizing functions

import numpy as np

def is_negative(x):
  if x < 0:
    return True
  else:
    return False

vec_is_negative = np.vectorize(is_negative) #vectorizing the function isNegative 
v = np.linspace(-5, 5, 5)
print(v)
print(vec_is_negative(v))

[-5.  -2.5  0.   2.5  5. ]
[ True  True False False False]


In [51]:
# Copying Arrays

import numpy as np

a = np.arange(6)
print("a =", a)
b = np.copy(a)       # a is copied in b
print("b =", b)
b[3] = 666      # changing in b will not change a

print("After replacing value in b")
print("a =", a) 
print("b =", b)

a = [0 1 2 3 4 5]
b = [0 1 2 3 4 5]
After replacing value in b
a = [0 1 2 3 4 5]
b = [  0   1   2 666   4   5]


In [52]:
x = np.arange(10)
y = x
y[4] = 24 
x[5] = 25
print(x)

[ 0  1  2  3 24 25  6  7  8  9]


In [54]:
# Accessing elements in 2 D array

import numpy as np

arr = np.array([[4, 2, 3, 2], [2, 4, 3, 1], [2, 4, 1, 3], [4, 1, 2, 3]])
print(arr)
print('the first row of arr')
print(arr[0])
print('the first column of arr')
print(arr[:, 0])
print('the third row of arr')
print(arr[2])
print('the last two columns of arr')
print(arr[:, -2:])
print('the four values in the upper right hand corner')
print(arr[:2, 2:])
print('the four values at the center of arr')
print(arr[1:3, 1:3])

[[4 2 3 2]
 [2 4 3 1]
 [2 4 1 3]
 [4 1 2 3]]
the first row of arr
[4 2 3 2]
the first column of arr
[4 2 2 4]
the third row of arr
[2 4 1 3]
the last two columns of arr
[[3 2]
 [3 1]
 [1 3]
 [2 3]]
the four values in the upper right hand corner
[[3 2]
 [3 1]]
the four values at the center of arr
[[4 3]
 [4 1]]


In [56]:
import numpy as np

x = np.linspace(0, 2 * np.pi, 20)
y = np.sin(x)

arr1 = y[(y > 0.7) | (y < -0.5)]
arr2 = y[(y > -0.5) & (y < 0.7)]

print(arr1)
print('-----')
print(arr2)

"""
In line 3, we have created an equally spaced array with 20 values ranging from 0
0 to 2\pi

.

In line 4, we have used x to generate y using the np.sin function.

In line 6, we have used the | operator to filter for elements that satisfy the condition y>0.7, \space y<-0.5
y>0.7, y<−0.5

In line 7, we have used the & operator to filter for elements that satisfy the condition -0.5<y<0.7
−0.5<y<0.7
"""

[ 0.83716648  0.96940027  0.99658449  0.91577333  0.73572391 -0.73572391
 -0.91577333 -0.99658449 -0.96940027 -0.83716648 -0.61421271]
-----
[ 0.00000000e+00  3.24699469e-01  6.14212713e-01  4.75947393e-01
  1.64594590e-01 -1.64594590e-01 -4.75947393e-01 -3.24699469e-01
 -2.44929360e-16]


'\nIn line 3, we have created an equally spaced array with 20 values ranging from 0\n0 to 2\\pi\n\n.\n\nIn line 4, we have used x to generate y using the np.sin function.\n\nIn line 6, we have used the | operator to filter for elements that satisfy the condition y>0.7, \\space y<-0.5\ny>0.7, y<−0.5\n\nIn line 7, we have used the & operator to filter for elements that satisfy the condition -0.5<y<0.7\n−0.5<y<0.7\n'